name: "Java - Test"

on:
  workflow_call:
    inputs:
      java_version:
        type: string
        default: "21"
      pom_path:
        type: string
        default: "pom.xml"
      test_command:
        type: string
        default: "mvn -B test"
      reports_artifact_name:
        type: string
        default: "test-reports"
    secrets:
      TEAMS_WEBHOOK_URL:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}
          cache: maven

      - name: Run Tests
        run: ${{ inputs.test_command }} -f ${{ inputs.pom_path }}

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.reports_artifact_name }}
          path: "**/target/surefire-reports/**"

  notify-failure:
    needs: test
    if: failure()
    uses: Bhuvaneshwaran-17/central-devops-tooling/.github/workflows/teams-notifier.yml@main
    with:
      project_name: "Java Unit Tests"
      # FIXED: Now using the dynamic input passed from the orchestrator
      component_name: "${{ inputs.reports_artifact_name }}"
      job_name: "Unit Test Execution"
      status: "FAILURE"
    secrets:
      WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}